name: build-AppImage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: beta-0.${{ github.run_number }}

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 1/21 * *" # We default to rebuilding every 21 days, change this to your liking
  workflow_dispatch: {}


jobs:
  build-prebuild-glibc:
    name: Build prebuild glibc
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v5
      - name: Install build tools
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update && apt-get install -y build-essential python3 gcc-10 g++-10 curl
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
      - name: build AM-GUI
        run: |     
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          . "$HOME/.nvm/nvm.sh"
          nvm install 22
          node -v
          npm -v
          npm install
          npx electron-rebuild
      - name: Upload prebuild
        uses: actions/upload-artifact@v5
        with:
          name: prebuild-glibc
          path: node_modules/node-pty/build/Release/pty.node

  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    needs: [build-prebuild-glibc]
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: Build AppImage
            arch: x86_64
          # comment out these 3 lines if aarch64 is not wanted
#          - runs-on: ubuntu-24.04-arm
#            name: Build AppImage
#            arch: aarch64 
        
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@v5
      - name: Preparing Container
        uses: pkgforge-dev/anylinux-setup-action@8872fabe63f9a00b35e25b2f46da62a05afc9a7d # v1
      - name: Setup Node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          . "$HOME/.nvm/nvm.sh"
          nvm install 22
          node -v
          npm -v      
          npm install
      - name: Download prebuild glibc
        uses: actions/download-artifact@v5
        with:
          name: prebuild-glibc
          path: temp-glibc
      - name: Place prebuild
        run: |
          mkdir -p node_modules/node-pty/build/Release
          cp temp-glibc/pty.node node_modules/node-pty/build/Release/pty.node
      - name: Run dist
        run: |
          . "$HOME/.nvm/nvm.sh"
          npm run dist
      - name: Install Dependencies
        run: /bin/sh ./scripts/get-dependencies.sh
      - name: Make AppImage
        run: /bin/sh ./scripts/make-appimage.sh
      - name: Upload artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: AppImage-${{ matrix.arch }}
          path: dist

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: AppImage-*
          merge-multiple: true
      - name: Release AppImage
        uses: pkgforge-dev/make-stable-appimage-release@4ed3d48ccb065352b6e6c0db6d39885b201c54a0 #v1.1
